export const FETCH_DOGS_START = 'FETCH_DOGS_START';
export const FETCH_DOGS_SUCCESS = 'FETCH_DOGS_SUCCESS';
export const FETCH_DOGS_FAILED = 'FETCH_DOGS_FAILED';
export const FETCH_ONE_DOG_START = 'FETCH_ONE_DOG_START';
export const FETCH_ONE_DOG_SUCCESS = 'FETCH_ONE_DOG_SUCCESS';
export const FETCH_ONE_DOG_FAILED = 'FETCH_ONE_DOG_FAILED';
